name: wyszukaj presence
version: "1.1.5"
slug: wyszukaj_presence
description: modół skanera sieci do wyszukaj presence w C++ ARP 
startup: services
boot: auto

host_network: true

privileged:
  - NET_RAW
  - NET_ADMIN

map:
  - type: homeassistant_config
    path: custom_components/wyszukaj_presence
    path_in_container: /wyszukaj_presence
    read_only: false

arch:
  - amd64
